blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://github.com/naretakis/mita-state-self-assessment-tool/tree/main/instructions
    about: Check the project documentation for detailed information
